### ISSUE TITLE
Usage of :output-to should trigger warning

### ISSUE THREAD

**Issue by jeluard** [adzerk-oss/boot-cljs#100]
I would expect `:output-to` value to be used and passed to the CLojureScript compiler but final name defaults to `main`.

**Comment by martinklepsch** [comment]
@jeluard are you using a `.cljs.edn` file to specify your build?

**Comment by jeluard** [comment]
No just the default configuration.

**Comment by Deraen** [comment]
`:output-to` is ignored always. Use `.cljs.edn` to set the output filename.

**Comment by jeluard** [comment]
Ok!

**Comment by martinklepsch** [comment]
I think we should leave this open and add a check if `:output-to` is used. If it's used we should let users know and tell them about using `.cljs.edn`.

**Comment by jeluard** [comment]
Relates to #94
