### ISSUE TITLE
How do I import different :externs for different boot tasks?

### ISSUE THREAD

**Issue by CodEFouR** [adzerk-oss/boot-cljs#112]
I'm trying to have a "dev" task which in my `build.boot`:
```
(deftask dev []
         (comp
           (serve)                                         
           (watch)                                        
           (speak)                                        
           (reload)                                        
           (cljs-repl)                                      
           (cljs :optimizations :none)))
```
And when I'm doing `boot dev`, I suppose the pretty js extern files included, e.g, `i18next.js`. When I deploy the project, I would like to have `i18next.min.js`. I'm trying to have different `.cljs.edn` and have a `:compiler-options` included like
`main-dev.cljs.edn` for development:
```
{:require [hello.core]
 :init-fns [hello.core/print-hello]
 :compiler-options {:asset-path "public/main-dev.out"
                              :externs ["public/i18next.min.js"]}}
```
`main.cljs.edn` for deployment:
```
{:require [tst.core]
 :init-fns [tst.core/print-hello]
 :compiler-options {:asset-path "public/main.out"
                             :externs ["public/i18next.js"]}}
```
But in my browser it never loads i18next extern file in either way. How could I do that? Thank you.

**Comment by martinklepsch** [comment]
@CodEFouR did you figure this out? I recommend reading up on foreign-libs support in ClojureScript, externs generally don't have minified versions as they're not included in the compiled artifact but just used during compilation.

**Comment by CodEFouR** [comment]
@martinklepsch Yes I get it solved... I thought the :externs would involve the closure compiler to merge the 3rd-party Javascript library, so I didn't put that Javascript in my HTML. Putting that file in my HTML solved the issue.

And thank you so much for your advice and I walked through the foreign-libs in ClojureScript, now I use foreign-libs to facilitate the closure compiler's power.

**Comment by CodEFouR** [comment]
@martinklepsch I think I misunderstood `:foreign-libs` because I found that my i18next library was not munged at all, with `:advanced` option enabled... I thought the closure compiler would optimize the `:foreign-libs` but it seems I was wrong. If I'm wrong here, I think I need to have two `.cljs.edn` with one of which I use the `.min.js` to have smaller code, and the other to include `.js` for easier debugging. Is my understanding above right?

And another issue I have is the i18next library creates a global object, `i18n`, and I need to call its method so I have like `(.init js/i18n args)` in my code, but when I have `:advanced` option the call would never be done. `js/i18n` could be found but not `(.init js/i18n args)`. Do you know why and how I could make it happen if I have `:advanced` option enabled?

**Comment by martinklepsch** [comment]
Foreign libs are not subject to optimizations. Read the `:foreign-libs` documentation to learn how you can supply minified and non minified libs. 

For Closure optimizations libraries have to be written in specific ways which most usual JS libs are not.

**Comment by martinklepsch** [comment]
> And another issue I have is the i18next library creates a global object, i18n, and I need to call its method so I have like (.init js/i18n args) in my code, but when I have :advanced option the call would never be done. js/i18n could be found but not (.init js/i18n args). Do you know why and how I could make it happen if I have :advanced option enabled?

This is caused because you need to have externs for this `init` function.

This is not related to boot-cljs, if you are on Slack I'd recommend asking in the #clojurescript channel. :)

**Comment by martinklepsch** [comment]
Maybe also the CLJSJS wiki can help you understand these requirements: https://github.com/cljsjs/packages/wiki

**Comment by CodEFouR** [comment]
@martinklepsch Thank you so much for your document links and yes, I think I understand this externs... By adding `deps.cljs` and `:externs` option it finally works. Thank you.
