### ISSUE TITLE
Support Closure modules

### ISSUE THREAD

**Issue by pandeiro** [adzerk-oss/boot-cljs#113]
The ClojureScript compiler this year included [support for Closure modules](https://github.com/clojure/clojurescript/wiki/Compiler-Options#modules), which allow an app's compiled JS output to be broken into several component artifacts. This can be a major improvement to the performance and efficiency of loading larger applications.

It would be great if boot-cljs could support this. Issue #104 seems tangentially related, in that the use of Closure modules seems to suggest either the user being able to specify output paths in some way (perhaps relative to Boot's tmp output directories), or boot-cljs somehow computing these values based on the information contained within a project's `.cljs.edn` files.

**Comment by codebeige** [comment]
+1

**Comment by magomimmo** [comment]
+1

**Comment by Deraen** [comment]
I propose supporting `:modules` key in `.cljs.edn`. `:output-to` would be ignored and set by boot-cljs and generated using the key in modules map.

**Comment by Deraen** [comment]
#114 contains experimental support for this.

**Comment by martinklepsch** [comment]
:clap:
