### ISSUE TITLE
boot-cljs does not work with build.boot

### ISSUE THREAD

**Issue by jongukim** [adzerk-oss/boot-cljs#123]
I made a build.boot as following: (from this [tutorial](https://github.com/magomimmo/modern-cljs/blob/master/doc/second-edition/tutorial-01.md))

```
(set-env!
  :source-paths #{"src/cljs"}
  :resource-paths #{"html"}
  :dependencies '[[adzerk/boot-cljs "1.7.228-1"]])

(require '[adzerk/boot-cljs :refer [cljs]])
```

When I run `boot -h`, I got an error message:

> $ boot -h
>    clojure.lang.ExceptionInfo: Could not locate boot_cljs__init.class or boot_cljs.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
>     data: {:file
>            "C:\\Users\\kju\\AppData\\Local\\Temp\\boot.user2089387444844651866.clj",
>            :line 7}
> java.io.FileNotFoundException: Could not locate boot_cljs__init.class or boot_cljs.clj on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.
>                                 ...

I could not find any clue so far.

When I run _boot_ with command line parameters, it works.
> $ boot -B -d adzerk/boot-cljs -s src/cljs -r html cljs target -d target
> Writing main.cljs.edn...
> Compiling ClojureScript...
> ? main.js
> Writing target dir(s)...

My boot configuration is: (**OS: Windows 10**)
> $ boot -V
> BOOT_CLOJURE_NAME=org.clojure/clojure
> BOOT_CLOJURE_VERSION=1.8.0
> BOOT_VERSION=2.5.5

and, I tried boot 2.6.0-SNAPSHOT, but got the same result.

**Comment by Deraen** [comment]
Notice dot instead of slash: `(require '[adzerk.boot-cljs :refer [cljs]])`

**Comment by jongukim** [comment]
Single typo ate up my 4 hours.
Thank you, @Deraen

**Comment by numinasthmatic** [comment]
I get the same problem with this build.boot:
`(set-env!
  :source-paths #{"src/cljs"}
  :resource-paths #{"html"}

  :dependencies '[[adzerk/boot-cljs "1.7.228-1"]]

  (require '[adzerk.boot-cljs :refer [cljs]]))`

I get the problem whether or not my ~/.boot/boot.properties contains this line
`BOOT_EMIT_TARGET=no`

As with the OP, using a full command line solves the problem.

**Comment by Deraen** [comment]
@numinasthmatic In the snippet you have the env parenthesis of set-env! in wrong place, after the require. If you have this same in the file, I would think it would give different error than the one in this issue, but I could be mistaken.
