### ISSUE TITLE
source-map-timestamp compiler option does nothing in advanced compilation

### ISSUE THREAD

**Issue by DomKM** [adzerk-oss/boot-cljs#127]
The [source-map-timestamp](https://github.com/clojure/clojurescript/wiki/Compiler-Options#source-map-timestamp) ClojureScript Compiler option seems to do nothing in advanced compilation. I don't know if this a ClojureScript bug, a boot-cljs bug, or a problem with my understanding of the issue.

**Comment by arichiardi** [comment]
Same with `:simple` here

**Comment by Deraen** [comment]
That option is only used with `:none` optimization:

- https://github.com/clojure/clojurescript/blob/f0b8531ab53ff2af0a47b122faac17feb1c36413/src/main/clojure/cljs/compiler.cljc#L1277
- https://github.com/clojure/clojurescript/blob/f0b8531ab53ff2af0a47b122faac17feb1c36413/src/main/clojure/cljs/compiler.cljc#L1211-L1226
