### ISSUE TITLE
Optimized build error

### ISSUE THREAD

**Issue by code-ape** [adzerk-oss/boot-cljs#130]
I have been developing a Reagent app and recently wanted to try out a production build of it. I have used the Tenzing Reagent template for this app and it's fairly simple. However I am getting bizarre Clojurescript behavior when I try to make a build.

The current issue I'm having is that when attempting to retrieve a nested value in a map I'm getting `nil` *only for the compiled version, not for the live repl version*. For reference the map is a returned value from cljs-http.client call to load an edn file which returns the following structure (omitting keys I'm not interested in):

```clojure
{:body
  {:content "String"}}
``` 

Currently this is what I get for each of the following:

|                             | live reload              | boot build target        |
|-----------------------------|--------------------------|--------------------------|
| `c`                           | `{:body {:content "String"}}` | `{:body {:content "String"}}` |
| `(-> c :body)`                | `{:content "String"}`         | `{:content "String"}`         |
| `(-> c :body :content)`       | `"String"`                    | `nil`                      |
| `(get-in c [:body :content])` | `"String"`                    | `nil`                      |

I have no idea what the difference is here but I've repeated this a number of times, cleaning the target directory and everything. This is both perplexing and annoying as I can't find a way to actually extract the string from the nested map in a build.

I'm happy to contribute any other data or information that is needed!

The code can be found here. It's just a single cljs file. The link goes to the method with this issue:
https://github.com/code-ape/website_builder/blob/1c003df8c1b499d40cdbcc3b51f6fc1020a53049/src/cljs/website/app.cljs#L11

Thanks for your time and help,
code-ape

**Comment by martinklepsch** [comment]
@code-ape thanks for the detailed description, could you update the github project with the build.boot you're using? Only thing I can think of would be a dependency issue. If you have `development` and `production` tasks you could try and see if there's a difference in the dependencies used.

```
boot development show -d
boot production show -d
```

**Comment by code-ape** [comment]
False alarm. The bug turned out to be with a difference in HTTP headers between my development and production server which impacted whether cljs-http.client does deserialization. Sorry for the trouble!

**Comment by martinklepsch** [comment]
@code-ape Thanks for reporting back! 👍  Closing this.
