### ISSUE TITLE
compatible with boot 2.6.0 ?

### ISSUE THREAD

**Issue by jiyinyiyong** [adzerk-oss/boot-cljs#131]
I posted some informations in https://clojurians.slack.com/messages/boot/details/ an this line throws errors running with boot `2.6.0`.

https://github.com/adzerk-oss/boot-cljs/blob/master/src/adzerk/boot_cljs.clj#L73
```clojure
      (swap! core/*warnings* + (or (count warnings) 0))
```

So question is that is it ready for boot `2.6.0`?

**Comment by Deraen** [comment]
Need more info. I have been using 2.6 since snapshots without problems.

**Comment by jiyinyiyong** [comment]
I can reproduce this by add unrecognised options to trigger the warnings. Can you confirm that warning is running correctly on your side?

**Comment by jiyinyiyong** [comment]
More details, `*warnings*` is initially empty https://github.com/boot-clj/boot/blob/94568ea09681bdeafaf9905f2ee601589bf135bf/boot/core/src/boot/core.clj#L35 but then bound to an Atom https://github.com/boot-clj/boot/blob/94568ea09681bdeafaf9905f2ee601589bf135bf/boot/core/src/boot/core.clj#L998 my friends guess that it's because my tasking is running in another thread(a handler of a jetty server) so it's not bound.

So, not `boot-cljs` bug, but triggered in using `boot-cljs`.

**Comment by jiyinyiyong** [comment]
A dirty fix on my side https://github.com/Cirru/boot-stack-server/commit/cf076bc9642c38d572c951ba8a80bcb6689c28d6
