### ISSUE TITLE
It tries to load a `/main.out/goog/base.js`

### ISSUE THREAD

**Issue by zilti** [adzerk-oss/boot-cljs#137]
I have a really quite simple setup. I've set my `cljs-src`-directory using `:source-paths`, placed my `main.cljs.edn` where I want the output .js to be, and have put `(cljs)`, without any arguments, into my command chain. The compilation works flawlessly without any warnings or errors.

But when I include it, it seems to request `/main.out/goog/base.js` and `/main.out/cljs_deps.js` while loading (and obviously fails). Why does it do that? I thought cljs compiles everything into one file?

**Comment by Deraen** [comment]
> I thought cljs compiles everything into one file?

No. In development node it will output a output file per namespace (and per used closure module), plus some additional files. Without knowing more, those paths seem correct.

Depending on what is the path you are serving files from, you might need to set asset-path  option manually: https://github.com/Deraen/saapas/blob/master/src/cljs/js/main.cljs.edn#L2

**Comment by zilti** [comment]
Ok. Asset-path is, I guess, a relative path to where I want the directory main.out to be?

**Comment by Deraen** [comment]
https://github.com/clojure/clojurescript/wiki/Compiler-Options#asset-path

**Comment by zilti** [comment]
This indeed corrected the link, but it still can't find the file now named `/data/js/goog/base.js`.

**Comment by zilti** [comment]
ahh, it creates the main.out directory inside the asset-path. :) Thanks!

**Comment by martinklepsch** [comment]
Can this be closed?
