### ISSUE TITLE
#!/usr/bin/env node in non-nodejs artifacts?

### ISSUE THREAD

**Issue by stephanos** [adzerk-oss/boot-cljs#36]
I think "0.0-2629-8" introduced a bug which emits "#!/usr/bin/env node" even for non-node artifacts.

**Comment by stephanos** [comment]
As a workaround, I added ':hashbang false' to the task's default settings.

**Comment by Deraen** [comment]
Can't reproduce, though this might be caused by multiple builds with different settings?

Reopen if this still happends.
