### ISSUE TITLE
Multiple incremental builds with different :target

### ISSUE THREAD

**Issue by smichal** [adzerk-oss/boot-cljs#55]
I have two `.cljs.edn` files, one targets browser and one with `:compiler-options {:target :nodejs}`. It worked great with CLJS 0.0-2740, but after https://github.com/clojure/clojurescript/commit/1611bdc7fa7ef21ed2e8543afaefd81b516bacec incremental compilation doesn't work. After each change there is full recompilation, first for browser and then with `{:target :nodejs}`.
Maybe for builds that differ in `build-affecting-options`, it should be separate context/:output-dir.

**Comment by WeweTom** [comment]
I have the same problem

**Comment by Deraen** [comment]
This will be eventually fixes by refactoring cljs task to only work using one build. But instead you'll be able to have multiple cljs task in your pipeline: `(comp (cljs :id "browser") (cljs :id "node"))`, where :ids would refer to specific .cljs.edn configurations.

**Comment by Deraen** [comment]
Should be fixed in master.
