### ISSUE TITLE
With multiple `.cljs.edn`s, each output js leaks into all subsequent outputs

### ISSUE THREAD

**Issue by mrcslws** [adzerk-oss/boot-cljs#61]
I really like the `.cljs.edn` approach to multiple targets. It's exactly what I was looking for. But... I don't think it's working if you use any optimization (I tried `:simple`, `:advanced`). Each target includes itself _and_ the previous target.

Looking at the js output for optimizations `:none`, the issue is occurring there too, but it's not run because the `goog.require` loads the correct namespace. 

I've tried using older versions to make sure this isn't another variant of #38 .

1. Clone https://github.com/adzerk/boot-cljs-example.git
2. Upgrade it to `[adzerk/boot-cljs "0.0-2814-3"] ;; latest release` to dodge other bugs
3. Add a simple alert function to `app.cljs`  
    ```  
    (defn my-alert []  
      (js/alert "You rang?"))  
    ```
4. Create two edn files:
  - Path: `html/aaa_not_included.cljs.edn` (intentionally first, alphabetically)  
    body:  `{:require [app] :init-fns [app/my-alert]}`
  - Path: `html/included.cljs.edn`  
    body: `{:require [app]}`
5. In `html/index.html` change `app.js` to `included.js`
6. `boot serve -d target/ watch speak reload cljs -sO simple`
7. Launch <http://localhost:3000/>

RESULT:
An alert pops up. Someone called `app/my-alert`!

**Comment by WeweTom** [comment]
I came to the same problem

**Comment by WeweTom** [comment]
so far , my  clojurescript experence is terible

**Comment by alandipert** [comment]
@mrcslws thank you for the detailed report, I was able to reproduce and fix.  The problem was compiler cache interference between independent builds.

**Comment by WeweTom** [comment]
It seems that the problem still exist

**Comment by alandipert** [comment]
@WeweTom I created https://github.com/alandipert/boot-cljs-reload-problem to attempt to reproduce but was not able.  I am using boot version rc13 on Linux.  Do you see the problem in that project on your system?

**Comment by martinklepsch** [comment]
I'm not sure if I did exactly the right steps but here's what I did:

```
> git clone git@github.com:alandipert/boot-cljs-reload-problem.git
> cd boot-cljs-reload-problem/
> boot serve -d target/ watch speak reload cljs -sO simple
```

After that I opened `http://localhost:3000` and saw no alert. 

```
Boot App Version: 2.0.0-rc12
Boot Lib Version: 2.0.0-rc12
Clojure Version:  1.6.0
```

**Comment by alandipert** [comment]
@martinklepsch thanks, yes that's what I've been doing too

**Comment by Yasushi** [comment]
I probably was able to reproduce on alandipert/boot-cljs-reload-problem .

<pre>
git clone https://github.com/alandipert/boot-cljs-reload-problem
cd boot-cljs-reload-problem
cp src/main.cljs.edn src/1.cljs.edn
cp src/main.cljs.edn src/2.cljs.edn
boot cljs -O none
</pre>

It generated boot-cljs-main.js is:
<pre>
[yasushi]% cat target/boot-cljs-main.js
goog.addDependency("base.js", ['goog'], []);
goog.addDependency("../cljs/core.js", ['cljs.core'], ['goog.string', 'goog.object', 'goog.string.StringBuffer', 'goog.array']);
goog.addDependency("../app/core.js", ['app.core'], ['cljs.core']);
goog.addDependency("../boot/cljs/2.js", ['boot.cljs.2'], ['cljs.core', 'app.core']);
goog.addDependency("../boot/cljs/included.js", ['boot.cljs.included'], ['cljs.core', 'app.core']);
goog.addDependency("../boot/cljs/1.js", ['boot.cljs.1'], ['cljs.core', 'app.core']);
goog.addDependency("../boot/cljs/aaa_not_included.js", ['boot.cljs.aaa_not_included'], ['cljs.core', 'app.core']);
goog.addDependency("../boot/cljs/main.js", ['boot.cljs.main'], ['cljs.core', 'app.core']);%                                             
</pre>

I think that it should not includes: `goog.addDependency("../boot/cljs/1.js"...` and `goog.addDependency("../boot/cljs/2.js",...`.

**Comment by WeweTom** [comment]
@alandipert I checkout your test repo , and it works now 

I formaly use `boot -s src watch cljs` with `:compiler-options {:optimizations :advanced}`

**Comment by Yasushi** [comment]
My comment is wrong. Sorry. 
It works correct.

**Comment by mrcslws** [comment]
I finally picked up `boot-cljs 0.0-2814-4`. Confirmed, this issue is fixed! Thanks!
