### ISSUE TITLE
Add support for official :main option

### ISSUE THREAD

**Issue by jeluard** [adzerk-oss/boot-cljs#62]
Recent versions of the ClojureScript compiler add support for a [main](https://github.com/clojure/clojurescript/wiki/Compiler-Options#main) option that is roughly equivalent to `.cljs.edn`.
When specified as part of `:compiler-options` the `.cljs.edn` handling should be skipped.

**Comment by Deraen** [comment]
I think we should generate a cljs namespace from `.cljs.edn` files and pass that to Cljs compiler. That way it's possible for boot-reload etc. to their code to the compilation.

**Comment by Deraen** [comment]
Latest version works now as described in my comment.

**Comment by jeluard** [comment]
I am right saying a `.cljs.edn` should always be present?

**Comment by Deraen** [comment]
Unless something broke, boot-cljs should create default one for you if you don't have one.

**Comment by jeluard** [comment]
Ok thanks!
