### ISSUE TITLE
2814-* builds broken URIs for foreign libs

### ISSUE THREAD

**Issue by ul** [adzerk-oss/boot-cljs#63]
E. g., if `:foreign-libs` contains entry

```
{:file     "jquery-ui.min.js"
:provides ["jquery.ui"]
:requires ["cljsjs.jquery"]}
```

then in browser console we can see 404 of http://localhost:3000/-p9hf6h/jquery-ui.min.js on page which depends on jquery.ui

With 2760-0 everything works fine, producing http://localhost:3000/js/out/jquery-ui.min.js

**Comment by Deraen** [comment]
Might work with the latest version.
