### ISSUE TITLE
Improve recompilation times

### ISSUE THREAD

**Issue by jeluard** [adzerk-oss/boot-cljs#65]
Using `boot-cljs` recompilation times are significantly slower than using `lein-cljsbuild`. With a project using `boot-cljx` with 100 files it takes 10-15s on my machine while the leiningen equivalent takes a couple second.

This issue is derived from #22 .

Which direction should I look at to eventually improve that? Note that the recompilation looks disk bound, CPU is pretty flat but disk busy.

**Comment by Deraen** [comment]
Could you test again with the latest version?

Also what is your environment?

**Comment by jeluard** [comment]
It looks like I still see slow recompiles on my OSX machine but I recently switched to a linux machine and this is not a problem for me anymore.
