### ISSUE TITLE
Developing against Clojure backend

### ISSUE THREAD

**Issue by wolverian** [adzerk-oss/boot-cljs#66]
I have a Clojure Ring handler as the backend serving the HTML and scripts, which I use via boot-http. The shim written by boot-cljs to `target/boot-cljs-main.js` requests an odd file from the server: `/Users/iv/.boot/cache/tmp/Users/iv/src/foo/7n7/dzj78b/out/cljs_deps.js`. I don't want my server to serve anything outside the project directory, so this request returns 404, which means my ClojureScript won't load. Anything I can do about this?

**Comment by myguidingstar** [comment]
try this option
https://github.com/clojure/clojurescript/wiki/Compiler-Options#asset-path
I made nodejs script run by using that option, too
