### ISSUE TITLE
Some guidance on what I should do?

### ISSUE THREAD

**Issue by samedhi** [adzerk-oss/boot-cljs#67]
So I am attempting some Chrome extension development. Chrome has specific Content Security Policy rules that forbid two things that boot-cljs does. 

1) By default, it is not permitted to use eval. This can be loosened by putting the following in your Chrome extension's `manifest.json` file. No real problem.
```
  "content_security_policy": "script-src 'self' 'unsafe-eval'; object-src 'self'"
```

2) The second issue is that it does not allow javascript inlined between a `script` tag. The only example of this I can find is in the following in `main.js` (generated with :optimizations :none).

```
  function writeScript(src) {
    var newElem;
    if (window.__boot_cljs_shim_loaded === undefined)
      document.write(src);
    else {
      newElem = document.createElement('div');
      newElem.innerHTML = src;
      if (newElem.src !== undefined && loaded[newElem.src] === undefined) {
        document.getElementsByTagName('head')[0].appendChild(newElem); }}}

  writeScript("<script src='" + prefix + "out/goog/base.js'></script>");
  writeScript("<script src='" + prefix + "boot-cljs-main.js'></script>");
  writeScript("<script>goog.require('boot.cljs.main');</script>");

  window.__boot_cljs_shim_loaded = true; })();
```

So, to fix this, after my code is generated, I then manually changed 
```
 writeScript("<script>goog.require('boot.cljs.main');</script>");
```
into
```
 writeScript("<script src="file_that_goog_requires_boot_cljs_main.js"></script>");
```
and added a file named `file_that_goog_requires_boot_cljs_main.js` that contains
```
goog.require('boot.cljs.main');
```

After making the above changes, I reload the extension and play with it. Cool. I can create a repl into the extension and execute code. Everything is good.

So, I know what to do, my question is how should I do it? Obviously manually editing the file every time is dumb. Should I create another task? Is there some way I could reach into boot-cljs and effect things? Is there some other totally evident option? Thank you for your time and help.

**Comment by Deraen** [comment]
Please test with latest version. Boot-cljs is no longer generating the shim but instead uses one generated by cljs compiler.

**Comment by Deraen** [comment]
Please reopen if still issue.
