### ISSUE TITLE
clojurescript tests

### ISSUE THREAD

**Issue by murtaza52** [adzerk-oss/boot-cljs#70]
Hi,

I want to write tests using clojurescript.test and run them using boot, however I am unable to find any info to do so. Could you please help ?

Thanks,
Murtaza

**Comment by crisptrutski** [comment]
@murtaza52 I created [https://github.com/crisptrutski/boot-cljs-test](boot-cljs-test) to scratch my own itch here.  The easiest way to get started using it is via [https://github.com/martinklepsch/tenzing](tenzing)  with the `+test` option.
