### ISSUE TITLE
Incorrect asset-path with latest releases

### ISSUE THREAD

**Issue by jeluard** [adzerk-oss/boot-cljs#72]
Generated `asset-path` is incorrect for my setup starting version `3269` and I get the infamous `ClojureScript could not load :main, did you forgot to specify :asset-path?`.

Previously the URLs generated in the initial js file included absolute paths while now they are relative to the current page. This does not work in my case as I have several different level of nesting all accessing the same js files.
Could this be made configurable for different cases? I also noticed you cannot provide your own `asset-path` value.

Incidentally I understand `boot-cljs` now directly relies on ClojureScript boot js file and does not generate its own shim? Is that right?

**Comment by Deraen** [comment]
Previously shim js created relative urls relative to html file in runtime using very magical JS trick to find the current <script> element in DOM. Now boot-cljs indeed uses shim generated by Cljs compiler which uses static :asset-path. Currently the option is set by boot-cljs and cannot be overwritten.

I can make the option configurable so you can configure absolute path yourself.

**Comment by jeluard** [comment]
It would definitively help to have it configurable.
