### ISSUE TITLE
Changing the output directory

### ISSUE THREAD

**Issue by yatesco** [adzerk-oss/boot-cljs#75]
If I specify:

:cljsbuild {                                                                                  
                        :builds [{:source-paths ["src/cljs" "src/cljc"]                                   
                                  :compiler {                                                             
                                             :output-to     "resources/public/out/main.js"                
                                             :output-dir    "resources/public/out"                        
                                             ;; figwheel needs this to be none                            
                                             :optimizations :none                                         
                                             :source-map    true}}]}  

in lein then the JS gets put into <project-dir>/resources/public/out however, if I pass the :compiler map as :compiler-options in boot-cljs the paths are relative to target (i.e. target/resources/public). 

Is this possible?

**Comment by Deraen** [comment]
You should not try to set `:output-to` or `:output-dir` using compiler-options in boot-cljs, they are set automatically (you can override them, but it probably wont work).

Instead, to control where the resulting js is written, move the `.cljs.edn` to wanted path.

E.g. if you want the output file to be `resources/public/main.js`, your `.cljs.edn` file should be `src/resources/public/main.cljs.edn`.

**Comment by rymndhng** [comment]
I found this frustrating and realized it didn't work through trial and error. Can we make this explicit in the README?

**Comment by wilkerlucio** [comment]
@Deraen I just tried your solution but it doesn't seem to work here.

I'm noticing that if I place the `.cljs.edn` file output of source path it's doesn't get detected...

There is any other way? I was thinking on having an extra build step to move the file outwards, I'm new to boot, is this approach indiomatic to boot?

Thanks.

**Comment by Deraen** [comment]
@wilkerlucio Additional step moving the files is ok, though it can require additional configuration in development mode (because created file assumes it's in certain path). 

Check these:
https://github.com/adzerk-oss/boot-cljs#multiple-builds
https://github.com/Deraen/saapas/blob/master/src/cljs/js/main.cljs.ednt

**Comment by thos37** [comment]
@Deraen wrote: "You should not try to set :output-to or :output-dir using compiler-options in boot-cljs, they are set automatically (you can override them, but it probably wont work)."

This method of only using files in the filesystem to configure compiler options seem counter-intuitive and very non-idiomatic.  It took me a while to figure out why (cljs :compiler-options { :output-to "path/to/public/js/main.js" }) was being ignored, and I'm sure others have had the same problem.  I think it's inappropriate to prevent the use of compiler options unless a boot user explicitly chooses to do this.  I see the rationale of having multiple builds as a secondary option, but not at the expense of access to the compiler options.  This also hinders usage of boot by developers coming from lein and cljs build scripts who expect to be able to set these options in the build file.  Can we default to allowing to set the compiler's options from within build.boot and only overriding them when someone explicitly creates a main.cljs.edn file, maybe even with a flag in the boot-cljs task that enables the user to choose?

**Comment by torgeir** [comment]
Agreed, this got me kinda stumped as well. I love the idea of keeping my build around as actual code, and in my case specifically, I was attempting share some of the compiler-options across my builds (a production one, a dev figwheel one etc) to prevent some of the repetition - being able to actually override e.g. :output-to and :output-dir would help for something like this.

**Comment by theronic** [comment]
Over the last year I estimate I have lost 40 hours trying to get boot-cljs to write JS to the right place and then trying to reference the asset-path correctly. I hope this configuration will become explicit ("put it here" or "sorry I don't know where to put this"), instead of implicit ("oh, I found a thing where I looked - let's put them here").
