### ISSUE TITLE
Compile only specific .cljs.edn builds

### ISSUE THREAD

**Issue by crisptrutski** [adzerk-oss/boot-cljs#77]
Being able to restrict what possible builds seems simpler than sifting the fileset, which will also affect downstream tasks. Perhaps this would take the form of providing a set of path strings and/or regexes.

My particular use case is having a generic `cljs-test` task, which currently has to strip all existing `.cljs.edn` files from the fileset to ensure a snappy build in projects with static build files (eg. those produced by tenzing).

Glad to provide a PR for this feature, but wanted to check if there's buy-in first.

**Comment by Deraen** [comment]
I have changes already planned and partially implemented which will affect this.

**Comment by crisptrutski** [comment]
Looking forward to your solution - 

Is the mechanism something similar (eg. associating ids with build files and filtering on those) or fundamentally different?

What does the timeline look like for releasing it?

Thanks for your great work here - let me know if I can help in any way

**Comment by Deraen** [comment]
Idea is similar. But in addition to ids `cljs` task will be refactored to only work with one id, instead produce multiple output files, you would combine multiple `cljs` tasks. This will make the task simpler. It will also make certain that different builds (with possible conflicting compiler options) don't share tempdirs.

**Comment by Deraen** [comment]
I have pushed the changes here: https://github.com/adzerk-oss/boot-cljs/compare/next

**Comment by crisptrutski** [comment]
Thanks for the update - sounds like a good approach to avoid confusing misuse. Will give that branch a whirl this evening.  One aspect I'm curious about it how much times are affected in the case of multiple files where compiler options are compatible - is this simplicity worth that hit? 

Also wonder if it isn't worth including a "sugar" task to build a series of ids.

Feel free to close this issue if you feel it's redundant!

**Comment by Deraen** [comment]
Implemented in master.
