### ISSUE TITLE
deps.cljs

### ISSUE THREAD

**Issue by ioRekz** [adzerk-oss/boot-cljs#78]
Hello,
I'm trying to add a single function to an extern file for a jquery plugin.
here is my /src/deps.cljs : 
```
{:externs ["wscratchpad.ext.js"]} 
```
It seems that there is no effect as I can write invalid edn code without getting any error.

**Comment by Deraen** [comment]
What do you mean invalid edn code without any error?

Also, externs are only used for advanced compilation.

**Comment by martinklepsch** [comment]
Are `deps.cljs` files picked up when they are directly in the source tree and not in a jar? 

Reading the question it's not clear if this is the source tree of a separate project or part of the project you want to use the foreign lib in.

**Comment by Deraen** [comment]
Yes, they are picked directly from the source tree (as described in the readme).

**Comment by martinklepsch** [comment]
Cool, I didn't see that section of the Readme before :)

**Comment by ioRekz** [comment]
I'm in advanced mode and my function call is munged so I'm trying to avoid it.
My deps.cljs is part of my project I want to use the foreign lib in.
This is not clear because I realize I don't get it myself. 

Here is the call that is now working in advanced compilation : 
```
(.wScratchPad (js/$ "#mydiv") xxxx)
```

**Comment by Deraen** [comment]
And what does the wscratchpad.ext.js contain?

**Comment by ioRekz** [comment]
jQuery.prototype.wScratchPad = function(a, b) {}

I've got it working by adding it to the cljs options with :externs ["wscratchpad.ext.js"]
In order to help, I think this is why I was confused about externs :
I almost started using clojurescript with Boot so every documentation I found about externs was based on lein-cljs. I took some time to realize that it was part of common google closure compiler options and wasn't specific to lein or boot.
When I understood the externs/foreign libs  concept I just checked the boot cljs readme and tried to use the deps.cljs without success.
Everything is properly working on advanced mode now. Thanks

**Comment by p14n** [comment]
I also struggled with deps.cljs before just adding it to my compiler ops - is the README wrong, misleading, or right in a way I didn't get?

**Comment by Deraen** [comment]
There is a working example in Saapas repo: https://github.com/Deraen/saapas/blob/master/src/cljs/deps.cljs

**Comment by danielsz** [comment]
I had the same problem with deps.cljs until I passed the map to :compiler-options. 
The only difference with saapas I could notice is that I don't use build is. deps.cljs in the top-level directory was being treated as a regular cljs file, yielding `no ns form found in file` error.

**Comment by Deraen** [comment]
@danielsz You don't have `.cljs.edn` at all? Default main should probably be fixed to ignore `deps.cljs` files: https://github.com/adzerk-oss/boot-cljs/blob/master/src/adzerk/boot_cljs.clj#L141

**Comment by danielsz** [comment]
That is correct. I don't have cljs.edn. 

If `cljs.edn` is mandatory for deps.cljs to be taken into account, README should mention that.

But it would be better if `deps.cljs` were detected in all cases.

**Comment by Deraen** [comment]
Default main will `:require` all cljs files in fileset so that's what is cauisng no ns form error. You could try using `(by-name (cljs-files fileset) ["deps.cljs"] true)` in `default-main`. It should filter deps.cljs files away.

**Comment by danielsz** [comment]
For local js files, I actually prefer to pass the foreign-libs map to compiler options.

> `deps.cljs` is a simple EDN file provided at the root of a JAR that
describes additional build information for the ClojureScript
compiler.

https://groups.google.com/forum/#!msg/clojurescript/pJ_EYHkYAUs/mLi8XfiQxZsJ

Please allow me to step back and ask the following: why should boot-cljs bother to support this?

**Comment by danielsz** [comment]
Maybe `cljs.edn` should have a foreign-libs option. Problem solved.

**Comment by Deraen** [comment]
I don't think there's any significant problems with this. `deps.cljs` already works fine with `.cljs.edn` files but there's a minor problem with default `.cljs.edn` generation which causes build to fail.

`:compiler-options` can be used from both the task and the `.cljs.edn` file to set the options.

**Comment by danielsz** [comment]
Ah, OK, so I'll update the README.

**Comment by Deraen** [comment]
@danielsz Could you try this instead: https://github.com/adzerk-oss/boot-cljs/commit/638d780d652416642ad831c46c45c654d5098c72 I think this should fix it.

**Comment by danielsz** [comment]
Something is not right.  
```java
java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.Boolean
```

**Comment by Deraen** [comment]
Ah, `by-name negate?` option doesn't work with `->>`. Hopefully is fixed now.

**Comment by danielsz** [comment]
Yup. This nails it. Thanks, @Deraen :+1:
