### ISSUE TITLE
HUD

### ISSUE THREAD

**Issue by Deraen** [adzerk-oss/boot-cljs#85]
Figwheel provides HUD which displays icon when it's doing reload and if warnings or errors happen it displays them. I find the warning & error display useful.

**Comment by martinklepsch** [comment]
:+1: I'd be happy to contribute the UI part of this. Not enough time right now to dig into the other bits. :(

**Comment by martinklepsch** [comment]
A rough idea for a possible approach:

- we add metadata about cljs compiler warnings somewhere where other tasks can see them (fileset metadata comes to mind but there might be other solutions)
- we use the existing websocket communication channel setup of the reload task to render some simple things to the DOM

@Deraen does that sound reasonable to you?

**Comment by Deraen** [comment]
Yes

**Comment by martinklepsch** [comment]
https://github.com/adzerk-oss/boot-cljs/pull/101 & https://github.com/adzerk-oss/boot-reload/pull/32

**Comment by Deraen** [comment]
Already implemented.
