### ISSUE TITLE
README says task takes parameter `id`, but code is checking `ids`

### ISSUE THREAD

**Issue by tvjg** [adzerk-oss/boot-cljs#88]
I was starting a fresh `build.boot` for a new project using the latest snapshot. I tried to use the `id` option/parameter [mentioned](https://github.com/adzerk-oss/boot-cljs#options) in the README. When it didn't appear to work, I checked the code. [It appears](https://github.com/adzerk-oss/boot-cljs/blob/master/src/adzerk/boot_cljs.clj#L170) that the `cljs` task is looking for `ids`. On the `next` branch, [it is checking](https://github.com/adzerk-oss/boot-cljs/blob/next/src/adzerk/boot_cljs.clj#L92) for `id`. Which is correct?

**Comment by Deraen** [comment]
:ids.

Fixes in readme.

**Comment by tvjg** [comment]
Thank you @Deraen !
