### ISSUE TITLE
UMD support with Clojurescript 1.7.132

### ISSUE THREAD

**Issue by thos37** [adzerk-oss/boot-cljs#96]
I just compiled Clojurescript 1.7.132 from source, which has support for Closure's new UMD module loading (see this page for context: http://mneise.github.io/posts/2015-07-08-week-6.html).  

When I use boot-cljs 1.7.48-3 and with the following task config in build.boot:

```clojure
    (cljs  :source-map true
          :optimizations :none
          :compiler-options {
            :warnings {:single-segment-namespace false}
            :foreign-libs [
                    {:file "resources/js/d3.js"
                      :provides ["d3"]
                      :module-type :commonjs}
            ]
          }
      )
```

It works!  (this was originally an error, but it was just a build.boot config error).

**Comment by thos37** [comment]
Here's a simple project that describes it: https://github.com/thos37/cljs-d3-umd

**Comment by alandipert** [comment]
Nice, thanks for sharing!
