### ISSUE TITLE
boot-cljs doesn't work with checkout

### ISSUE THREAD

**Issue by myguidingstar** [adzerk-oss/boot-cljs#97]
after updating to the latest boot-cljs, it yells to me
```
No such namespace: public.js.lib.out-prod.cljs.core.async.impl.channels, could not locate public/js/lib/out_prod/cljs/core/async/impl/channels.cljs, public/js/lib/out_prod/cljs/core/async/impl/channels.cljc, or Closure namespace "public.js.lib.out-prod.cljs.core.async.impl.channels"
```
if I comment out the checkout task, cljs can compile normally.
those weird namespaces are generated in main.cljs.edn by default-main task

**Comment by martinklepsch** [comment]
I think pasting the task definitions and `cljs` task options would be helpful. I remember getting similar errors but I don't exactly remember what the problem was.

**Comment by xificurC** [comment]
Last time this happened to me I had some leftover files in resource- or source-paths.

**Comment by myguidingstar** [comment]
```clj
(deftask dev []
  (comp (watch)
        ;; the Ring handler to use
        (serve :handler 'ona.server.main/app :reload true)
        ;; will work if comment out
        (checkout :dependencies '[[org.clojars.onaio/hatti "0.1.7-SNAPSHOT"]
                                  [onaio/milia "0.2.5"]])
        (speak)
        ;; :on-jsload will be needed when the Cljs app has an init
        ;; function, especially when we use Om
        ;; (reload :on-jsload 'app.core/main)
        (reload :port 3456 :asset-path "/public")
        (cljs-repl :port 3457)
        (cljs :source-map true :optimizations :none
              :compiler-options {:asset-path "/js/lib/main.out"})
        (sift :move {#"^main.js"  "public/js/lib/main.js"
                     #"^main.out" "public/js/lib/main.out"})))
```

**Comment by myguidingstar** [comment]
seems to go away after last version

**Comment by myguidingstar** [comment]
It hit me again today. Look like if the checkout dependencies is not available in the local machine and requires some time to fetch, checkout task will cause trouble...

**Comment by myguidingstar** [comment]
look like this is a checkout problem, will file an issue in Boot

**Comment by Deraen** [comment]
How can it be possible that the dependencies are not already downloaded when the task runs? Aren't the depenencies in your `:dependencies` vector?

**Comment by myguidingstar** [comment]
they are both in my deps and checkout
