### ISSUE TITLE
Optimization none output directory

### ISSUE THREAD

**Issue by taylorSando** [adzerk-oss/boot-cljs#99]
I have this:

``` clojure
(cljs :optimizations :none :unified-mode true :ids ["js/dev"])
```

It outputs to /target/js/dev.js
It also creates a /target/js/dev.out directory with all the dev files

Including /js/dev.js in the html file causes these scripts to be created:
```html
<script src="dev.out/goog/base.js"></script>
<script src="dev.out/cljs_deps.js"></script>
```

Which is great when I'm at the root url, but if I try to use a different url, the dev.out files aren't loaded properly, since it's trying to load them relatively to the url.

**Comment by Deraen** [comment]
In this case you have to manually set `:compiler-options :asset-path`, probably value `"/dev.out/"` should work for absolute url.

PS. Unified-mode option doesn't exist anymore.

**Comment by taylorSando** [comment]
I changed the the dev.cljs.edn file to this:
```clojure
{:require [dev.workzone.config]
 :compiler-options {:asset-path "/js/dev.out"} 
 :init-fns [dev.workzone.config/main]}
```

It now loads properly.
